### ISSUE TITLE
Add description for mods

### ISSUE THREAD

**Issue by NotLe0n** [NotLe0n/ModStats#11]
- query http://javid.ddns.net/tModLoader/tools/querymodnamehomepagedescription.php separately from the mod info query
- select correct mod
- change description innerHTML

**Comment by SheepishShepherd** [comment]
Make description fit within its section. Currently the description goes off screen until a new line occurs.

**Comment by NotLe0n** [comment]
> Make description fit within its section. Currently the description goes off screen until a new line occurs.

there is a horizontal scrollbar to see everything. I didn't want to move the description below the download graph because I want everything to fit into one page (on a 1080p monitor)
